AllCops:
  TargetRubyVersion: 2.7
  Include:
    - '**/*.rb'
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/rakefile'
  Exclude:
    - '_node/**/*'
    - 'vendor/**/*'
  NewCops: enable

Metrics/LineLength:
  Max: 126

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/FirstArrayElementIndentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/TernaryParentheses:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Lint/SuppressedException:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false
